{
   "deposit";[
      {
         "user_id":"jWCi1eEXNvLiDwsW97jii8ZGTQoTW8d5fqZtaFYV",
         "currency":"USD",
         "amount":10
      },
      {
         "user_id":"XkVcwxL8kyT29IpNVcD1Ii9zftm32bmNxe1H9IN9",
         "currency":"EUR",
         "amount":15
      },
      {
         "user_id":"BbV9NEp0xmb8eJmQnHiLVgf1DtXyCtPKeUadmk2P",
         "currency":"EUR",
         "amount":15
      },
      {
         "user_id":"BbV9NEp0xmb8eJmQnHiLVgf1DtXyCtPKeUadmk2P",
         "currency":"USD",
         "amount":10
      }
   ],
   "withdrawal";[
      {
         "user_id":"jWCi1eEXNvLiDwsW97jii8ZGTQoTW8d5fqZtaFYV",
         "currency":"USD",
         "amount":10
      },
      {
         "user_id":"BbV9NEp0xmb8eJmQnHiLVgf1DtXyCtPKeUadmk2P",
         "currency":"EUR",
         "amount":15
      },
      {
         "user_id":"BbV9NEp0xmb8eJmQnHiLVgf1DtXyCtPKeUadmk2P",
         "currency":"USD",
         "amount":10
      },
      {
         "user_id":"FQmgI63mlgGmLiKxOoUNAASTZRmbSmuBNTbvhDlM",
         "currency":"USD",
         "amount":10
      },
      {
         "user_id":"k8dN9SE9YISzCQJ55PLJ8ep7rVbvACK932aWLUTo",
         "currency":"USD",
         "amount":10
      }
   ]
}